### ISSUE TITLE
Add explicit guidance for the "recommended labels" for system components

### ISSUE THREAD

**Issue by tcdowney** [cloudfoundry-incubator/kubernetes-guidelines#4]
The guidelines recommend that system components adopt the [Kubernetes Recommended Labels](https://kubernetes.io/docs/concepts/overview/working-with-objects/common-labels/#labels), however it does not mentioned what values these labels should have. Since one use-case for these is to provide operators with a convenient way to list every resource associated with a particular "deployment" of resources (e.g. show many everything that belongs to "Cloud Foundry") we need some of these values to be consistent across components.

Take the `app.kubernetes.io/part-of` label, for example. Some components might set its value to `cf`, others to `cloudfoundry`, and others to `Cloud Foundry`. Likewise, for labels like `app.kubernetes.io/instance` or `app.kubernetes.io/version` it is ambiguous as to what these actually refer to. We should make sure components are consistently referring to the same thing when they choose to set these labels.

As a straw-dog proposal, these are the values we're going with for the `Route` custom resource for the time being:

```yaml
   app.kubernetes.io/name: <cc-route-guid>
   app.kubernetes.io/version: <cloud-controller-api-version>
   app.kubernetes.io/managed-by: cloudfoundry # (some debate whether this should be `capi` or `cloud_controller_ng`
   app.kubernetes.io/component: cf-networking
   app.kubernetes.io/part-of: cloudfoundry
```

Even while providing this example we noticed some further ambiguities. Maybe the `app.kubernetes.io/managed-by` label has a different meaning depending on the context. On a custom resource managed by a component perhaps it should refer to the component that created it. But for a `Deployment` or `Pod` or something that is actually running the system component it should refer back to the actual "deployment" and would be `app.kubernetes.io/managed-by: cloudfoundry` or something. 🤔 

We'd like to get feedback and thoughts from other component teams to help us all settle on some more concrete conventions here.

Thanks!
Tim && @ndhanushkodi

---

For context, we started having this discussion in several places already:
* [cf-k8s-networking Route CRD doc](https://docs.google.com/document/d/1DF7eTBut1I74w_sVaQ4eeF74iQes1nG3iUv7iJ7E35U/edit?disco=AAAAGUduewg)
* https://github.com/cloudfoundry/cf-k8s-networking/pull/25
